# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opcua_webapi.models.action_method_data_type import ActionMethodDataType

class TestActionMethodDataType(unittest.TestCase):
    """ActionMethodDataType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActionMethodDataType:
        """Test ActionMethodDataType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActionMethodDataType`
        """
        model = ActionMethodDataType()
        if include_optional:
            return ActionMethodDataType(
                object_id = '',
                method_id = ''
            )
        else:
            return ActionMethodDataType(
        )
        """

    def testActionMethodDataType(self):
        """Test ActionMethodDataType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
