# coding: utf-8

"""
    OPC UA Web API

    This API provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from opcua_webapi.models.user_token_type import UserTokenType  # noqa: E501

class TestUserTokenType(unittest.TestCase):
    """UserTokenType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserTokenType(self):
        """Test UserTokenType"""
        # inst = UserTokenType()

if __name__ == '__main__':
    unittest.main()
