# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opcua_webapi.models.write_request import WriteRequest

class TestWriteRequest(unittest.TestCase):
    """WriteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WriteRequest:
        """Test WriteRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WriteRequest`
        """
        model = WriteRequest()
        if include_optional:
            return WriteRequest(
                request_header = opcua_webapi.models.request_header.RequestHeader(
                    authentication_token = '', 
                    timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    request_handle = 0, 
                    return_diagnostics = 0, 
                    audit_entry_id = '', 
                    timeout_hint = 0, 
                    additional_header = opcua_webapi.models.extension_object.ExtensionObject(
                        ua_type_id = '', 
                        ua_encoding = 0, 
                        ua_body = 'YQ==', ), ),
                nodes_to_write = [
                    opcua_webapi.models.write_value.WriteValue(
                        node_id = '', 
                        attribute_id = 0, 
                        index_range = '', 
                        value = opcua_webapi.models.data_value.DataValue(
                            ua_type = 0, 
                            dimensions = [
                                0
                                ], 
                            status_code = opcua_webapi.models.status_code.StatusCode(
                                code = 0, 
                                symbol = '', ), 
                            source_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            source_picoseconds = 0, 
                            server_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            server_picoseconds = 0, ), )
                    ]
            )
        else:
            return WriteRequest(
        )
        """

    def testWriteRequest(self):
        """Test WriteRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
