# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opcua_webapi.models.json_data_set_message import JsonDataSetMessage

class TestJsonDataSetMessage(unittest.TestCase):
    """JsonDataSetMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JsonDataSetMessage:
        """Test JsonDataSetMessage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JsonDataSetMessage`
        """
        model = JsonDataSetMessage()
        if include_optional:
            return JsonDataSetMessage(
                data_set_writer_id = 0,
                data_set_writer_name = '',
                publisher_id = '',
                writer_group_name = '',
                sequence_number = 0,
                meta_data_version = opcua_webapi.models.configuration_version_data_type.ConfigurationVersionDataType(
                    major_version = 0, 
                    minor_version = 0, ),
                minor_version = 0,
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = opcua_webapi.models.status_code.StatusCode(
                    code = 0, 
                    symbol = '', ),
                message_type = '',
                payload = opcua_webapi.models.extension_object.ExtensionObject(
                    ua_type_id = '', 
                    ua_encoding = 0, 
                    ua_body = 'YQ==', )
            )
        else:
            return JsonDataSetMessage(
        )
        """

    def testJsonDataSetMessage(self):
        """Test JsonDataSetMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
