# coding: utf-8

"""
    OPC UA Web API

    This API provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from opcua_webapi.models.call_method_request import CallMethodRequest  # noqa: E501

class TestCallMethodRequest(unittest.TestCase):
    """CallMethodRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CallMethodRequest:
        """Test CallMethodRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CallMethodRequest`
        """
        model = CallMethodRequest()  # noqa: E501
        if include_optional:
            return CallMethodRequest(
                object_id = '',
                method_id = '',
                input_arguments = [
                    opcua_webapi.models.variant.Variant(
                        type = 0, 
                        body = null, 
                        dimensions = [
                            0
                            ], )
                    ]
            )
        else:
            return CallMethodRequest(
        )
        """

    def testCallMethodRequest(self):
        """Test CallMethodRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
