# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opcua_webapi.models.monitoring_parameters import MonitoringParameters

class TestMonitoringParameters(unittest.TestCase):
    """MonitoringParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MonitoringParameters:
        """Test MonitoringParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MonitoringParameters`
        """
        model = MonitoringParameters()
        if include_optional:
            return MonitoringParameters(
                client_handle = 0,
                sampling_interval = 1.337,
                filter = opcua_webapi.models.extension_object.ExtensionObject(
                    ua_type_id = '', 
                    ua_encoding = 0, 
                    ua_body = 'YQ==', ),
                queue_size = 0,
                discard_oldest = True
            )
        else:
            return MonitoringParameters(
        )
        """

    def testMonitoringParameters(self):
        """Test MonitoringParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
