# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opcua_webapi.models.json_action_network_message import JsonActionNetworkMessage

class TestJsonActionNetworkMessage(unittest.TestCase):
    """JsonActionNetworkMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JsonActionNetworkMessage:
        """Test JsonActionNetworkMessage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JsonActionNetworkMessage`
        """
        model = JsonActionNetworkMessage()
        if include_optional:
            return JsonActionNetworkMessage(
                message_id = '',
                message_type = '',
                publisher_id = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                response_address = '',
                correlation_data = 'YQ==',
                requestor_id = '',
                timeout_hint = 1.337,
                messages = [
                    None
                    ]
            )
        else:
            return JsonActionNetworkMessage(
        )
        """

    def testJsonActionNetworkMessage(self):
        """Test JsonActionNetworkMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
