# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opcua_webapi.models.read_at_time_details import ReadAtTimeDetails

class TestReadAtTimeDetails(unittest.TestCase):
    """ReadAtTimeDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReadAtTimeDetails:
        """Test ReadAtTimeDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReadAtTimeDetails`
        """
        model = ReadAtTimeDetails()
        if include_optional:
            return ReadAtTimeDetails(
                req_times = [
                    datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
                    ],
                use_simple_bounds = True
            )
        else:
            return ReadAtTimeDetails(
        )
        """

    def testReadAtTimeDetails(self):
        """Test ReadAtTimeDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
