# coding: utf-8

"""
    OPC UA Web API

    This API provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from opcua_webapi.models.monitoring_mode import MonitoringMode  # noqa: E501

class TestMonitoringMode(unittest.TestCase):
    """MonitoringMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMonitoringMode(self):
        """Test MonitoringMode"""
        # inst = MonitoringMode()

if __name__ == '__main__':
    unittest.main()
