# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opcua_webapi.models.history_read_value_id import HistoryReadValueId

class TestHistoryReadValueId(unittest.TestCase):
    """HistoryReadValueId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HistoryReadValueId:
        """Test HistoryReadValueId
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HistoryReadValueId`
        """
        model = HistoryReadValueId()
        if include_optional:
            return HistoryReadValueId(
                node_id = '',
                index_range = '',
                data_encoding = '',
                continuation_point = 'YQ=='
            )
        else:
            return HistoryReadValueId(
        )
        """

    def testHistoryReadValueId(self):
        """Test HistoryReadValueId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
