# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opcua_webapi.models.field_meta_data import FieldMetaData

class TestFieldMetaData(unittest.TestCase):
    """FieldMetaData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FieldMetaData:
        """Test FieldMetaData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FieldMetaData`
        """
        model = FieldMetaData()
        if include_optional:
            return FieldMetaData(
                name = '',
                description = opcua_webapi.models.localized_text.LocalizedText(
                    locale = '', 
                    text = '', ),
                field_flags = 0,
                built_in_type = 0,
                data_type = '',
                value_rank = 56,
                array_dimensions = [
                    0
                    ],
                max_string_length = 0,
                data_set_field_id = '',
                properties = [
                    opcua_webapi.models.key_value_pair.KeyValuePair(
                        key = '', 
                        value = opcua_webapi.models.variant.Variant(
                            ua_type = 0, 
                            dimensions = [
                                0
                                ], ), )
                    ]
            )
        else:
            return FieldMetaData(
        )
        """

    def testFieldMetaData(self):
        """Test FieldMetaData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
