# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opcua_webapi.models.json_action_response_message import JsonActionResponseMessage

class TestJsonActionResponseMessage(unittest.TestCase):
    """JsonActionResponseMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JsonActionResponseMessage:
        """Test JsonActionResponseMessage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JsonActionResponseMessage`
        """
        model = JsonActionResponseMessage()
        if include_optional:
            return JsonActionResponseMessage(
                data_set_writer_id = 0,
                action_target_id = 0,
                data_set_writer_name = '',
                writer_group_name = '',
                meta_data_version = opcua_webapi.models.configuration_version_data_type.ConfigurationVersionDataType(
                    major_version = 0, 
                    minor_version = 0, ),
                minor_version = 0,
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = opcua_webapi.models.status_code.StatusCode(
                    code = 0, 
                    symbol = '', ),
                message_type = '',
                request_id = 0,
                action_state = 56,
                payload = None
            )
        else:
            return JsonActionResponseMessage(
        )
        """

    def testJsonActionResponseMessage(self):
        """Test JsonActionResponseMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
