# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opcua_webapi.models.data_change_trigger import DataChangeTrigger

class TestDataChangeTrigger(unittest.TestCase):
    """DataChangeTrigger unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataChangeTrigger(self):
        """Test DataChangeTrigger"""
        # inst = DataChangeTrigger()

if __name__ == '__main__':
    unittest.main()
