# coding: utf-8

"""
    OPC UA Web API

    This API provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
from setuptools import setup, find_packages  # noqa: H301

NAME = "opcua-webapi"
VERSION = "1.504.0"
PYTHON_REQUIRES = ">=3.7"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "pydantic >= 1.10.5, < 2",
    "aenum"
]

setup(
    name=NAME,
    version=VERSION,
    description="OPC UA Web API",
    author="OpenAPI Generator community",
    author_email="office@opcfoundation.org",
    url="https://github.com/opcfoundation-org/opcua-webapi-python/",
    keywords=["OpenAPI", "OpenAPI-Generator", "OPC UA Web API"],
    python_requires=PYTHON_REQUIRES,
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="OPC Source Deliverable Agreement of Use",
    long_description_content_type='text/markdown',
    long_description="""\
    This API provides simple HTTPS based access to an OPC UA server.
    """,  # noqa: E501
    package_data={"opcua_webapi": ["py.typed"]},
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
)
