# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class AggregateConfiguration(BaseModel):
    """
    [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part11/6.5.4/#6.5.4.1).
    """ # noqa: E501
    use_server_capabilities_defaults: Optional[StrictBool] = Field(default=False, alias="UseServerCapabilitiesDefaults")
    treat_uncertain_as_bad: Optional[StrictBool] = Field(default=False, alias="TreatUncertainAsBad")
    percent_data_bad: Optional[Annotated[int, Field(le=255, strict=True, ge=0)]] = Field(default=0, alias="PercentDataBad")
    percent_data_good: Optional[Annotated[int, Field(le=255, strict=True, ge=0)]] = Field(default=0, alias="PercentDataGood")
    use_sloped_extrapolation: Optional[StrictBool] = Field(default=False, alias="UseSlopedExtrapolation")
    __properties: ClassVar[List[str]] = ["UseServerCapabilitiesDefaults", "TreatUncertainAsBad", "PercentDataBad", "PercentDataGood", "UseSlopedExtrapolation"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AggregateConfiguration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AggregateConfiguration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "UseServerCapabilitiesDefaults": obj.get("UseServerCapabilitiesDefaults") if obj.get("UseServerCapabilitiesDefaults") is not None else False,
            "TreatUncertainAsBad": obj.get("TreatUncertainAsBad") if obj.get("TreatUncertainAsBad") is not None else False,
            "PercentDataBad": obj.get("PercentDataBad") if obj.get("PercentDataBad") is not None else 0,
            "PercentDataGood": obj.get("PercentDataGood") if obj.get("PercentDataGood") is not None else 0,
            "UseSlopedExtrapolation": obj.get("UseSlopedExtrapolation") if obj.get("UseSlopedExtrapolation") is not None else False
        })
        return _obj


