# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from opcua_webapi.models.key_value_pair import KeyValuePair
from typing import Optional, Set
from typing_extensions import Self

class DataSetWriterDataType(BaseModel):
    """
    [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part14/6.2.4/#6.2.4.5.1).
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, alias="Name")
    enabled: Optional[StrictBool] = Field(default=False, alias="Enabled")
    data_set_writer_id: Optional[Annotated[int, Field(le=65535, strict=True, ge=0)]] = Field(default=0, alias="DataSetWriterId")
    data_set_field_content_mask: Optional[Annotated[int, Field(le=4294967295, strict=True, ge=0)]] = Field(default=0, alias="DataSetFieldContentMask")
    key_frame_count: Optional[Annotated[int, Field(le=4294967295, strict=True, ge=0)]] = Field(default=0, alias="KeyFrameCount")
    data_set_name: Optional[StrictStr] = Field(default=None, alias="DataSetName")
    data_set_writer_properties: Optional[List[KeyValuePair]] = Field(default=None, alias="DataSetWriterProperties")
    transport_settings: Optional[Dict[str, Any]] = Field(default=None, alias="TransportSettings")
    message_settings: Optional[Dict[str, Any]] = Field(default=None, alias="MessageSettings")
    __properties: ClassVar[List[str]] = ["Name", "Enabled", "DataSetWriterId", "DataSetFieldContentMask", "KeyFrameCount", "DataSetName", "DataSetWriterProperties", "TransportSettings", "MessageSettings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DataSetWriterDataType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in data_set_writer_properties (list)
        _items = []
        if self.data_set_writer_properties:
            for _item_data_set_writer_properties in self.data_set_writer_properties:
                if _item_data_set_writer_properties:
                    _items.append(_item_data_set_writer_properties.to_dict())
            _dict['DataSetWriterProperties'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DataSetWriterDataType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Name": obj.get("Name"),
            "Enabled": obj.get("Enabled") if obj.get("Enabled") is not None else False,
            "DataSetWriterId": obj.get("DataSetWriterId") if obj.get("DataSetWriterId") is not None else 0,
            "DataSetFieldContentMask": obj.get("DataSetFieldContentMask") if obj.get("DataSetFieldContentMask") is not None else 0,
            "KeyFrameCount": obj.get("KeyFrameCount") if obj.get("KeyFrameCount") is not None else 0,
            "DataSetName": obj.get("DataSetName"),
            "DataSetWriterProperties": [KeyValuePair.from_dict(_item) for _item in obj["DataSetWriterProperties"]] if obj.get("DataSetWriterProperties") is not None else None,
            "TransportSettings": obj.get("TransportSettings"),
            "MessageSettings": obj.get("MessageSettings")
        })
        return _obj


