# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class HistoryUpdateType(int, Enum):
    """
    [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part11/6.7).
    """

    """
    allowed enum values
    """
    Insert = 1
    Replace = 2
    Update = 3
    Delete = 4

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HistoryUpdateType from a JSON string"""
        return cls(json.loads(json_str))


