# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from opcua_webapi.models.extension_object import ExtensionObject
from opcua_webapi.models.history_read_value_id import HistoryReadValueId
from opcua_webapi.models.request_header import RequestHeader
from typing import Optional, Set
from typing_extensions import Self

class HistoryReadRequest(BaseModel):
    """
    [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/5.11.3/#5.11.3.2).
    """ # noqa: E501
    request_header: Optional[RequestHeader] = Field(default=None, alias="RequestHeader")
    history_read_details: Optional[ExtensionObject] = Field(default=None, alias="HistoryReadDetails")
    timestamps_to_return: Optional[StrictInt] = Field(default=None, description="[Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/7.40).", alias="TimestampsToReturn")
    release_continuation_points: Optional[StrictBool] = Field(default=False, alias="ReleaseContinuationPoints")
    nodes_to_read: Optional[List[HistoryReadValueId]] = Field(default=None, alias="NodesToRead")
    __properties: ClassVar[List[str]] = ["RequestHeader", "HistoryReadDetails", "TimestampsToReturn", "ReleaseContinuationPoints", "NodesToRead"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HistoryReadRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of request_header
        if self.request_header:
            _dict['RequestHeader'] = self.request_header.to_dict()
        # override the default output from pydantic by calling `to_dict()` of history_read_details
        if self.history_read_details:
            _dict['HistoryReadDetails'] = self.history_read_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in nodes_to_read (list)
        _items = []
        if self.nodes_to_read:
            for _item_nodes_to_read in self.nodes_to_read:
                if _item_nodes_to_read:
                    _items.append(_item_nodes_to_read.to_dict())
            _dict['NodesToRead'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HistoryReadRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "RequestHeader": RequestHeader.from_dict(obj["RequestHeader"]) if obj.get("RequestHeader") is not None else None,
            "HistoryReadDetails": ExtensionObject.from_dict(obj["HistoryReadDetails"]) if obj.get("HistoryReadDetails") is not None else None,
            "TimestampsToReturn": obj.get("TimestampsToReturn"),
            "ReleaseContinuationPoints": obj.get("ReleaseContinuationPoints") if obj.get("ReleaseContinuationPoints") is not None else False,
            "NodesToRead": [HistoryReadValueId.from_dict(_item) for _item in obj["NodesToRead"]] if obj.get("NodesToRead") is not None else None
        })
        return _obj


