# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class JsonMessageType(str, Enum):
    """
    JsonMessageType
    """

    """
    allowed enum values
    """
    UA_MINUS_DATA = 'ua-data'
    UA_MINUS_METADATA = 'ua-metadata'
    UA_MINUS_APPLICATION = 'ua-application'
    UA_MINUS_ENDPOINTS = 'ua-endpoints'
    UA_MINUS_STATUS = 'ua-status'
    UA_MINUS_CONNECTION = 'ua-connection'
    UA_MINUS_ACTION_MINUS_REQUEST = 'ua-action-request'
    UA_MINUS_ACTION_MINUS_RESPONSE = 'ua-action-response'
    UA_MINUS_ACTION_MINUS_METADATA = 'ua-action-metadata'
    UA_MINUS_ACTION_MINUS_RESPONDER = 'ua-action-responder'
    UA_MINUS_KEYFRAME = 'ua-keyframe'
    UA_MINUS_DELTAFRAME = 'ua-deltaframe'
    UA_MINUS_EVENT = 'ua-event'
    UA_MINUS_KEEPALIVE = 'ua-keepalive'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of JsonMessageType from a JSON string"""
        return cls(json.loads(json_str))


