# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class JsonMessageType(str, Enum):
    """
    JsonMessageType
    """

    """
    allowed enum values
    """
    Data = 'ua-data'
    DataSetMetadata = 'ua-metadata'
    Application = 'ua-application'
    Endpoints = 'ua-endpoints'
    Status = 'ua-status'
    Connection = 'ua-connection'
    ActionRequest = 'ua-action-request'
    ActionResponse = 'ua-action-response'
    ActionMetadata = 'ua-action-metadata'
    ActionResponder = 'ua-action-responder'
    KeyFrame = 'ua-keyframe'
    DeltaFrame = 'ua-deltaframe'
    Event = 'ua-event'
    KeepAlive = 'ua-keepalive'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of JsonMessageType from a JSON string"""
        return cls(json.loads(json_str))


