# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class JsonStatusMessage(BaseModel):
    """
    [Link to specification]().
    """ # noqa: E501
    message_id: Optional[StrictStr] = Field(default=None, alias="MessageId")
    message_type: Optional[StrictStr] = Field(default=None, alias="MessageType")
    publisher_id: Optional[StrictStr] = Field(default=None, alias="PublisherId")
    timestamp: Optional[datetime] = Field(default=None, alias="Timestamp")
    is_cyclic: Optional[StrictBool] = Field(default=False, alias="IsCyclic")
    status: Optional[StrictInt] = Field(default=None, description="[Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part14/6.2.1).", alias="Status")
    next_report_time: Optional[datetime] = Field(default=None, alias="NextReportTime")
    __properties: ClassVar[List[str]] = ["MessageId", "MessageType", "PublisherId", "Timestamp", "IsCyclic", "Status", "NextReportTime"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JsonStatusMessage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JsonStatusMessage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "MessageId": obj.get("MessageId"),
            "MessageType": obj.get("MessageType"),
            "PublisherId": obj.get("PublisherId"),
            "Timestamp": obj.get("Timestamp"),
            "IsCyclic": obj.get("IsCyclic") if obj.get("IsCyclic") is not None else False,
            "Status": obj.get("Status"),
            "NextReportTime": obj.get("NextReportTime")
        })
        return _obj


