# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from opcua_webapi.models.monitoring_parameters import MonitoringParameters
from opcua_webapi.models.read_value_id import ReadValueId
from typing import Optional, Set
from typing_extensions import Self

class MonitoredItemCreateRequest(BaseModel):
    """
    [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/5.13.2/#5.13.2.2).
    """ # noqa: E501
    item_to_monitor: Optional[ReadValueId] = Field(default=None, alias="ItemToMonitor")
    monitoring_mode: Optional[StrictInt] = Field(default=None, description="[Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/7.23).", alias="MonitoringMode")
    requested_parameters: Optional[MonitoringParameters] = Field(default=None, alias="RequestedParameters")
    __properties: ClassVar[List[str]] = ["ItemToMonitor", "MonitoringMode", "RequestedParameters"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MonitoredItemCreateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of item_to_monitor
        if self.item_to_monitor:
            _dict['ItemToMonitor'] = self.item_to_monitor.to_dict()
        # override the default output from pydantic by calling `to_dict()` of requested_parameters
        if self.requested_parameters:
            _dict['RequestedParameters'] = self.requested_parameters.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MonitoredItemCreateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ItemToMonitor": ReadValueId.from_dict(obj["ItemToMonitor"]) if obj.get("ItemToMonitor") is not None else None,
            "MonitoringMode": obj.get("MonitoringMode"),
            "RequestedParameters": MonitoringParameters.from_dict(obj["RequestedParameters"]) if obj.get("RequestedParameters") is not None else None
        })
        return _obj


