# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from opcua_webapi.models.key_value_pair import KeyValuePair
from opcua_webapi.models.user_token_policy import UserTokenPolicy
from typing import Optional, Set
from typing_extensions import Self

class PubSubKeyPushTargetDataType(BaseModel):
    """
    PubSubKeyPushTargetDataType
    """ # noqa: E501
    application_uri: Optional[StrictStr] = Field(default=None, alias="ApplicationUri")
    push_target_folder: Optional[List[StrictStr]] = Field(default=None, alias="PushTargetFolder")
    endpoint_url: Optional[StrictStr] = Field(default=None, alias="EndpointUrl")
    security_policy_uri: Optional[StrictStr] = Field(default=None, alias="SecurityPolicyUri")
    user_token_type: Optional[UserTokenPolicy] = Field(default=None, alias="UserTokenType")
    requested_key_count: Optional[Annotated[int, Field(le=65535, strict=True, ge=0)]] = Field(default=None, alias="RequestedKeyCount")
    retry_interval: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="RetryInterval")
    push_target_properties: Optional[List[KeyValuePair]] = Field(default=None, alias="PushTargetProperties")
    security_groups: Optional[List[StrictStr]] = Field(default=None, alias="SecurityGroups")
    __properties: ClassVar[List[str]] = ["ApplicationUri", "PushTargetFolder", "EndpointUrl", "SecurityPolicyUri", "UserTokenType", "RequestedKeyCount", "RetryInterval", "PushTargetProperties", "SecurityGroups"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PubSubKeyPushTargetDataType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of user_token_type
        if self.user_token_type:
            _dict['UserTokenType'] = self.user_token_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in push_target_properties (list)
        _items = []
        if self.push_target_properties:
            for _item_push_target_properties in self.push_target_properties:
                if _item_push_target_properties:
                    _items.append(_item_push_target_properties.to_dict())
            _dict['PushTargetProperties'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PubSubKeyPushTargetDataType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ApplicationUri": obj.get("ApplicationUri"),
            "PushTargetFolder": obj.get("PushTargetFolder"),
            "EndpointUrl": obj.get("EndpointUrl"),
            "SecurityPolicyUri": obj.get("SecurityPolicyUri"),
            "UserTokenType": UserTokenPolicy.from_dict(obj["UserTokenType"]) if obj.get("UserTokenType") is not None else None,
            "RequestedKeyCount": obj.get("RequestedKeyCount"),
            "RetryInterval": obj.get("RetryInterval"),
            "PushTargetProperties": [KeyValuePair.from_dict(_item) for _item in obj["PushTargetProperties"]] if obj.get("PushTargetProperties") is not None else None,
            "SecurityGroups": obj.get("SecurityGroups")
        })
        return _obj


