# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from opcua_webapi.models.data_set_meta_data_type import DataSetMetaDataType
from opcua_webapi.models.key_value_pair import KeyValuePair
from typing import Optional, Set
from typing_extensions import Self

class PublishedDataSetDataType(BaseModel):
    """
    [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part14/6.2.3/#6.2.3.5).
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, alias="Name")
    data_set_folder: Optional[List[StrictStr]] = Field(default=None, alias="DataSetFolder")
    data_set_meta_data: Optional[DataSetMetaDataType] = Field(default=None, alias="DataSetMetaData")
    extension_fields: Optional[List[KeyValuePair]] = Field(default=None, alias="ExtensionFields")
    data_set_source: Optional[Dict[str, Any]] = Field(default=None, alias="DataSetSource")
    __properties: ClassVar[List[str]] = ["Name", "DataSetFolder", "DataSetMetaData", "ExtensionFields", "DataSetSource"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PublishedDataSetDataType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of data_set_meta_data
        if self.data_set_meta_data:
            _dict['DataSetMetaData'] = self.data_set_meta_data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in extension_fields (list)
        _items = []
        if self.extension_fields:
            for _item_extension_fields in self.extension_fields:
                if _item_extension_fields:
                    _items.append(_item_extension_fields.to_dict())
            _dict['ExtensionFields'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PublishedDataSetDataType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Name": obj.get("Name"),
            "DataSetFolder": obj.get("DataSetFolder"),
            "DataSetMetaData": DataSetMetaDataType.from_dict(obj["DataSetMetaData"]) if obj.get("DataSetMetaData") is not None else None,
            "ExtensionFields": [KeyValuePair.from_dict(_item) for _item in obj["ExtensionFields"]] if obj.get("ExtensionFields") is not None else None,
            "DataSetSource": obj.get("DataSetSource")
        })
        return _obj


