# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from opcua_webapi.models.data_set_reader_data_type import DataSetReaderDataType
from opcua_webapi.models.endpoint_description import EndpointDescription
from opcua_webapi.models.extension_object import ExtensionObject
from opcua_webapi.models.key_value_pair import KeyValuePair
from typing import Optional, Set
from typing_extensions import Self

class ReaderGroupDataType(BaseModel):
    """
    ReaderGroupDataType
    """ # noqa: E501
    transport_settings: Optional[ExtensionObject] = Field(default=None, alias="TransportSettings")
    message_settings: Optional[ExtensionObject] = Field(default=None, alias="MessageSettings")
    data_set_readers: Optional[List[DataSetReaderDataType]] = Field(default=None, alias="DataSetReaders")
    name: Optional[StrictStr] = Field(default=None, alias="Name")
    enabled: Optional[StrictBool] = Field(default=None, alias="Enabled")
    security_mode: Optional[StrictInt] = Field(default=None, alias="SecurityMode")
    security_group_id: Optional[StrictStr] = Field(default=None, alias="SecurityGroupId")
    security_key_services: Optional[List[EndpointDescription]] = Field(default=None, alias="SecurityKeyServices")
    max_network_message_size: Optional[Annotated[int, Field(le=4294967295, strict=True, ge=0)]] = Field(default=None, alias="MaxNetworkMessageSize")
    group_properties: Optional[List[KeyValuePair]] = Field(default=None, alias="GroupProperties")
    __properties: ClassVar[List[str]] = ["Name", "Enabled", "SecurityMode", "SecurityGroupId", "SecurityKeyServices", "MaxNetworkMessageSize", "GroupProperties"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReaderGroupDataType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in security_key_services (list)
        _items = []
        if self.security_key_services:
            for _item_security_key_services in self.security_key_services:
                if _item_security_key_services:
                    _items.append(_item_security_key_services.to_dict())
            _dict['SecurityKeyServices'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in group_properties (list)
        _items = []
        if self.group_properties:
            for _item_group_properties in self.group_properties:
                if _item_group_properties:
                    _items.append(_item_group_properties.to_dict())
            _dict['GroupProperties'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReaderGroupDataType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Name": obj.get("Name"),
            "Enabled": obj.get("Enabled"),
            "SecurityMode": obj.get("SecurityMode"),
            "SecurityGroupId": obj.get("SecurityGroupId"),
            "SecurityKeyServices": [EndpointDescription.from_dict(_item) for _item in obj["SecurityKeyServices"]] if obj.get("SecurityKeyServices") is not None else None,
            "MaxNetworkMessageSize": obj.get("MaxNetworkMessageSize"),
            "GroupProperties": [KeyValuePair.from_dict(_item) for _item in obj["GroupProperties"]] if obj.get("GroupProperties") is not None else None
        })
        return _obj


