# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from opcua_webapi.models.diagnostic_info import DiagnosticInfo
from opcua_webapi.models.response_header import ResponseHeader
from opcua_webapi.models.status_code import StatusCode
from typing import Optional, Set
from typing_extensions import Self

class SetTriggeringResponse(BaseModel):
    """
    SetTriggeringResponse
    """ # noqa: E501
    response_header: Optional[ResponseHeader] = Field(default=None, alias="ResponseHeader")
    add_results: Optional[List[StatusCode]] = Field(default=None, alias="AddResults")
    add_diagnostic_infos: Optional[List[DiagnosticInfo]] = Field(default=None, alias="AddDiagnosticInfos")
    remove_results: Optional[List[StatusCode]] = Field(default=None, alias="RemoveResults")
    remove_diagnostic_infos: Optional[List[DiagnosticInfo]] = Field(default=None, alias="RemoveDiagnosticInfos")
    __properties: ClassVar[List[str]] = ["ResponseHeader", "AddResults", "AddDiagnosticInfos", "RemoveResults", "RemoveDiagnosticInfos"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SetTriggeringResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of response_header
        if self.response_header:
            _dict['ResponseHeader'] = self.response_header.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in add_results (list)
        _items = []
        if self.add_results:
            for _item_add_results in self.add_results:
                if _item_add_results:
                    _items.append(_item_add_results.to_dict())
            _dict['AddResults'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in add_diagnostic_infos (list)
        _items = []
        if self.add_diagnostic_infos:
            for _item_add_diagnostic_infos in self.add_diagnostic_infos:
                if _item_add_diagnostic_infos:
                    _items.append(_item_add_diagnostic_infos.to_dict())
            _dict['AddDiagnosticInfos'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in remove_results (list)
        _items = []
        if self.remove_results:
            for _item_remove_results in self.remove_results:
                if _item_remove_results:
                    _items.append(_item_remove_results.to_dict())
            _dict['RemoveResults'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in remove_diagnostic_infos (list)
        _items = []
        if self.remove_diagnostic_infos:
            for _item_remove_diagnostic_infos in self.remove_diagnostic_infos:
                if _item_remove_diagnostic_infos:
                    _items.append(_item_remove_diagnostic_infos.to_dict())
            _dict['RemoveDiagnosticInfos'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SetTriggeringResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ResponseHeader": ResponseHeader.from_dict(obj["ResponseHeader"]) if obj.get("ResponseHeader") is not None else None,
            "AddResults": [StatusCode.from_dict(_item) for _item in obj["AddResults"]] if obj.get("AddResults") is not None else None,
            "AddDiagnosticInfos": [DiagnosticInfo.from_dict(_item) for _item in obj["AddDiagnosticInfos"]] if obj.get("AddDiagnosticInfos") is not None else None,
            "RemoveResults": [StatusCode.from_dict(_item) for _item in obj["RemoveResults"]] if obj.get("RemoveResults") is not None else None,
            "RemoveDiagnosticInfos": [DiagnosticInfo.from_dict(_item) for _item in obj["RemoveDiagnosticInfos"]] if obj.get("RemoveDiagnosticInfos") is not None else None
        })
        return _obj


