# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TimestampsToReturn(int, Enum):
    """
    TimestampsToReturn
    """

    """
    allowed enum values
    """
    Source = 0
    Server = 1
    Both = 2
    Neither = 3
    Invalid = 4

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TimestampsToReturn from a JSON string"""
        return cls(json.loads(json_str))


