# coding: utf-8

"""
    OPC UA Web API

    Provides simple HTTPS based access to an OPC UA server.

    The version of the OpenAPI document: 1.05.4
    Contact: office@opcfoundation.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class UserTokenType(int, Enum):
    """
    UserTokenType
    """

    """
    allowed enum values
    """
    Anonymous = 0
    UserName = 1
    Certificate = 2
    IssuedToken = 3

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UserTokenType from a JSON string"""
        return cls(json.loads(json_str))


